### ISSUE TITLE
System User not able to change password

### ISSUE THREAD

**Issue by Fredoluka** [MohammadAhmad1990/erpnext_quota#19]
I have noticed that a system user cannot change his password in Erpnext version 14 which has the quota app installed. An error message "Insufficient Permission for Has Role" occurs whenever he tries to save the changed password. I think it is applicable to any modification a user wants to do on his or her user page.
When I uninstall the quota app, the issue stops.
Thanks

**Comment by thekingchild** [comment]
@ahmadpak Thanks for fixing previous issues. I have similar issue. Social Logins are not working and triggers "You do not have enough permissions to complete the action", and stock balance report also triggered the following error. 

`Traceback (most recent call last):
File "apps/frappe/frappe/core/doctype/prepared_report/prepared_report.py", line 44, in run_background
create_json_gz_file(result["result"], "Prepared Report", instance.name)
File "apps/frappe/frappe/core/doctype/prepared_report/prepared_report.py", line 136, in create_json_gz_file
_file.save(ignore_permissions=True)
File "apps/frappe/frappe/model/document.py", line 305, in save
return self._save(*args, **kwargs)
File "apps/frappe/frappe/model/document.py", line 327, in _save
return self.insert()
File "apps/frappe/frappe/model/document.py", line 259, in insert
self.run_before_save_methods()
File "apps/frappe/frappe/model/document.py", line 1040, in run_before_save_methods
self.run_method("validate")
File "apps/frappe/frappe/model/document.py", line 909, in run_method
out = Document.hook(fn)(self, *args, **kwargs)
File "apps/frappe/frappe/model/document.py", line 1259, in composer
return composed(self, method, *args, **kwargs)
File "apps/frappe/frappe/model/document.py", line 1243, in runner
add_to_return_value(self, f(self, method, *args, **kwargs))
File "apps/erpnext_quota/erpnext_quota/erpnext_quota/quota.py", line 70, in files_space_limit
validate_files_space_limit()
File "apps/erpnext_quota/erpnext_quota/erpnext_quota/quota.py", line 113, in validate_files_space_limit
frappe.throw(_(msg))
UnboundLocalError: local variable 'msg' referenced before assignment`

**Comment by ahmadpak** [comment]
@femijoshuao fixed for 

1. develop
2. version-14
